const districtEle = document.getElementById("district");
const municipalityOption = document.getElementById("p-municipality");

function clickedRadio(x) {
  if (x.value == "somedays" || x.value == "everyday") {
    document.getElementById("smoke").style.display = "block";
  } else if (x.value == "drinkalcohol") {
    document.getElementById("drink").style.display = "block";
  } else if (x.value == "comorbid") {
    document.getElementById("specifyComorbid").style.display = "block";
  } else if (x.value == "homeIso") {
    document.getElementById("hospitalized").style.display = "none";
    document.getElementById("dateOfHospitalization").style.display = "none";
    document.getElementById("symptoms").style.display = "block";
  } else if (x.value == "hospitalized") {
    document.getElementById("dateOfHospitalization").style.display = "block";
  } else if (x.value == "yesSymptoms") {
    document.getElementById("mildSymptoms").style.display = "block";
    document.getElementById("severeSymptoms").style.display = "block";
  } else if (x.value == "yesMedication") {
    document.getElementById("whichMedication").style.display = "block";
  } else if (x.value == "nosmoke") {
    document.getElementById("smoke").style.display = "none";
  } else if (x.value == "nodrinkalcohol") {
    document.getElementById("drink").style.display = "none";
  } else if (x.value == "nocomorbid") {
    document.getElementById("specifyComorbid").style.display = "none";
  } else if (x.value == "noHomeIso") {
    document.getElementById("hospitalized").style.display = "block";
    document.getElementById("symptoms").style.display = "none";
    document.getElementById("mildSymptoms").style.display = "none";
    document.getElementById("severeSymptoms").style.display = "none";
  } else if (x.value == "noHospitalized") {
    document.getElementById("dateOfHospitalization").style.display = "none";
  } else if (x.value == "noSymptoms") {
    document.getElementById("mildSymptoms").style.display = "none";
    document.getElementById("severeSymptoms").style.display = "none";
  } else if (x.value == "noMedication") {
    document.getElementById("whichMedication").style.display = "none";
    document.getElementById("allopathicDrug").style.display = "none";
    document.getElementById("herbalMed").style.display = "none";
    document.getElementById("otherMed").style.display = "none";
  } else if (x.value == "Allopatic") {
    document.getElementById("allopathicDrug").style.display = "block";
    document.getElementById("herbalMed").style.display = "none";
    document.getElementById("otherMed").style.display = "none";
  } else if (x.value == "Herbal") {
    document.getElementById("herbalMed").style.display = "block";
    document.getElementById("allopathicDrug").style.display = "none";
    document.getElementById("otherMed").style.display = "none";
  } else if (x.value == "OtherMed") {
    document.getElementById("otherMed").style.display = "block";
    document.getElementById("allopathicDrug").style.display = "none";
    document.getElementById("herbalMed").style.display = "none";
  }
}

const municipalityDetails = {
  achham:['Babala','Baijinath','Bannatoli','Baradadivi','Basti','Batulasen','Bayala','Bhagyaswori','Bhairabsthan','Bhatakatiya','Bhuli','Binayak','Bindhyawasini','Birpath','Budhakot','Chalsa','Chandika(Bayalpata)','Chaphamandau','Darna','Devisthan','Dhakari','Dhaku','Dhamali','Dhodasain','Dhudharukot','Dhungachalna','Duni','Gajara','Hatikot','Hichma','Jalapadevi','Janalibandali','Janalikot','Jupu','Kalagau','Kalekanda','Kalika','Kalikasthan','Khaptad','Khodasadevi','Kuika','Kuntibandali','Kushkot','Layati','Lungra','Malatikot','Mangalsen','Marku','Mashtanamdali','Mastamandau','Nada','Nandegada','Nawathana','Oligau','Patalkot','Payal','Pulletala','Rahaph','Ramarosan','Raniban','Ridikot','Risidaha','Santada','Sera','Siddheswor','Siudi','Soukat','Sutar','Thanti','Timilsain','Toli','Tosi','Turmakhad','Walant','Warla',],
  arghakhanchi:['Adguri','Argha','Arghatos','Asurkot','Balkot','Bangi','Bangla','Bhagawati','Chhatraganj','Chidika','Dhakawang','Dhanchaur','Dharapani','Dhatiwang','Dhikura','Dibharna','Gorkhunga','Hansapur','Jukena','Juluke','Keemadada','Kerunga','Khan','Khanchikot','Khandaha','Khidim','Khilji','Maidan','Mareng','Narapani','Nuwakot','Pali','Pathauti','Pathona','Pokharathok','Sandhikharka','Siddhara','Simalapani','Sitapur','Subarnakhal','Thada','Thulapokhara'],
  baglung:['Akhikarichaur', 'Amalachaur', 'Amarbhumi', 'Argal', 'Arjewa', 'Batakachaur', 'Bhakunde', 'Bhimpokhara', 'Bhinggithe', 'Bihunkot', 'Binamare', 'Boharagaun', 'Bongadovan', 'Bowang', 'Burtiwang', 'Chhisti', 'Dagatundada', 'Damek', 'Darling', 'Devisthan', 'Dhamja', 'Dhudhilabhati', 'Dhullugaidi', 'Dhullubaskot', 'Gwalichaur', 'Harichaur', 'Hatiya', 'Heel', 'Hugdisheer', 'Jaljala', 'Baglung Municipality', 'Kandebas', 'Khunga', 'Kusmishera', 'Lekhani', 'Malika', 'Malma', 'Narayansthan', 'Narethanti', 'Nisi', 'Paiyunpata', 'Paiyunthanthap', 'Palakot', 'Pandavkhani', 'Rajkut', 'Ranasinkiteni', 'Rangkhani', 'Rayadanda', 'Resh', 'Righa', 'Salyan', 'Sarkuwa', 'Singana', 'Sisakhani', 'Sukhaura', 'Sunkhani', 'Taman', 'Tangram', 'Tara', 'Tityang'],
  baitadi:['Amchaur', 'Basantapur', 'Basuling', 'Bhatana', 'Bhumeswor', 'Bijayapur', 'Bilashpur', 'Bumiraj', 'Chaukham', 'Dasharathchand Municipality', 'Dehimandau', 'Deulek', 'Dhikarim/Rim', 'Dhikasintad/Sitad', 'Dhungad', 'Dilasaini', 'Durgabhabani', 'Durgasthan', 'Gajari', 'Giregada', 'Gokuleswor', 'Gujar', 'Gurukhola', 'Gwallek', 'Hat', 'Hatraj', 'Kaipal', 'Kataujpani', 'Kotila', 'Kotpetara', 'Kulau', 'Kuwakot', 'Mahadevsthan', 'Mahakali', 'Maharudra', 'Malladehi', 'Mathairaj', 'Maunali', 'Melauli', 'Nagarjun', 'Nwadeu', 'Nwali', 'Pancheswor', 'Patan', 'Raudidewal', 'Rauleswor', 'Rudreswor', 'Sakar', 'Salena', 'Sarmali', 'Shankarpur', 'Shibanath', 'Shikharpur', 'Shivaling', 'Siddhapur', 'Siddheswor', 'Sikash', 'Silanga', 'Sreekedar', 'Sreekot', 'Talladehi', 'Thalakanda', 'Udayadeb'],
  bajhang:['Banjh','Bhairabanath','Bhamchaur','Bhatekhola','Byasi','Chainpur','Chaudhari','Dahabagar','Dangaji','Dantola','Daulichaur','Deulekh','Deulikot','Dhamena','Gadaraya','Hemantabada','Kadel','Kailash','Kalukheti','Kanda','Kaphalaseri','Khiratadi','Koiralakot','Kotbhairab','Kotdewal','Lamatola','Lekhgau','Luyanta','Majhigau','Malumela','Mashdev','Matela','Maulali','Melbisauni','Parakatne','Patadewal','Pauwagadhi','Pipalkot','Rayal','Rilu','Rithapata','Sainpasela','Subeda','Sunikot','Sunkuda','Surma','Syandi'],
  bajura:['Atichaur','Baddhu','Bai','Barhabise','Bichhaiyan','Bramhatola','Budhiganga','Chhatara','Dahakot','Dogadi','Gotree','Gudukhati','Jagannath','Jayabageswori','Jugada','Jukot','Kailashmandau','Kanda','Kolti','Kotila','Kuldeumadau','Manakot','Martadi','Pandusain','Rugin','Sapata','Tolidewal'],
  banke:['Bageswari', 'Banakatawa', 'Banakatti', 'Basudevapur', 'Bejapur', 'Belahari', 'Belbhar', 'Betahani', 'Bhawaniyapur', 'Binauna', 'Chisapani', 'Ganapur', 'Gangapur', 'Hirminiya', 'Holiya', 'Indarpur', 'Jaispur', 'Kalaphanta', 'Kamdi', 'Kanchanapur', 'Kathkuiya', 'Khajurakhurda', 'Khaskarkado', 'Khaskusma', 'Kohalpur', 'Laxmanpur', 'Mahadevpuri', 'Manikapur', 'Matahiya', 'Narainapur', 'Naubasta', 'Nepalganj Municipality', 'Paraspur', 'Phatepur', 'Piparhawa', 'Puraina', 'Puraini', 'Radhapur', 'Rajhena', 'Raniyapur', 'Saigaun', 'Samserganj', 'Sitapur', 'Sonapur', 'Titihiriya', 'Udarapur', 'Udayapur'],
  bara:['Amarpatti', 'Amlekhganj', 'Amritgang', 'Avab', 'Babuain', 'Bachhanpurwa', 'Badakifulbariya', 'Bagahi', 'Bahuari', 'Balirampur', 'Bandhuwan', 'Banjariya', 'Barainiya', 'Bariyarpur', 'Basantpur', 'Batara', 'Beldari', 'Benauli', 'Bhagwanpur', 'Bhaluyeearwaliya', 'Bharatganjsigaul', 'Bhatauda', 'Bhodaha', 'Bishrampur', 'Bishunpur', 'Bishunpurwa', 'Buniyad', 'Chhatapipra', 'Chhatawa', 'Dahiyar', 'Dewapur', 'Dharmanagar', 'Dohari', 'Dumarwana', 'Fattepur', 'Gadhahal', 'Ganjbhawanipur', 'Golaganj', 'Haraiya', 'Hardiya', 'Hariharpur', 'Inarwamal', 'Inarwasira', 'Itiyahi', 'Jhitakaiya(Dakshin)', 'Jhitakaiya(Uttar)', 'Jitpurbhawanipur', 'Kabahigoth', 'Kabahijabdi', 'Kachorwa', 'Kakadi', 'Kalaiya Municipality', 'Karaiya', 'Khopawa', 'Khutwajabdi', 'Kolhabi', 'Kudawa', 'Laxmipurkotwali', 'Lipanimal', 'Madhurijabdi', 'Mahendraadarsha', 'Maheshpur', 'Majhariya', 'Manaharwa', 'Matiarwa', 'Motisar', 'Narahi', 'Nijgadh', 'Pakadiyachikani', 'Paparpatijabdi', 'Paterwa', 'Patharhati', 'Pathera', 'Pheta', 'Piparasimara', 'Piparabirta', 'Piparpatiparchrouwa', 'Piprabasantapur', 'Pipradhigoth', 'Prasauni', 'Prasona', 'Prastoka', 'Prasurmpur', 'Purainiya', 'Raghunathpur', 'Rampurtokani', 'Rampurwa', 'Ratanpuri', 'Rauwahi', 'Sapahi', 'Shreenagarbairiya', 'Sihorwa', 'Sinhasani', 'Sisahaniya', 'Tedhakatti', 'Telkuwa', 'Tetariya', 'Uchidiha', 'Umarjan'],
  bardiya:['Badalpur', 'Baganaha', 'Baniyabhar', 'Belawa', 'Bhimapur', 'Daulatpur', 'Deudakala', 'Dhadhawar', 'Dhodhari', 'Gola', 'Gulariya Municipality', 'Jamuni', 'Kalika', 'Khairichandanpur', 'Magaragadi', 'Mahamadpur', 'Manpurmainapokhar', 'Manau', 'Manpurtapara', 'Motipur', 'Nayagaun', 'Neulapur', 'Padanaha', 'Pasupatinagar', 'Patabhar', 'Rajapur', 'Sanashree', 'Sivapur', 'Sorhawa', 'Suryapatawa', 'Taratal', 'Thakudwara'],
  bhaktapur:['Bageswori', 'Balkot', 'Bhaktapur Municipality', 'Changunarayan', 'Chhaling', 'Chitapol', 'Dadhikot', 'Duwakot', 'Gundu', 'Jhaukhel', 'Kautunje', 'Madhyapur Thimi Municipality', 'Nagarkot', 'Nankhel', 'Sipadol', 'Sirutar', 'Sudal', 'Tathali'],
  bhojpur:['Aamtep','Annapurna','Baikuntha','Basikhola','Basingtharpur','Basteem','Bhaisipankha','Bhojpur','Bhubal(Yoon)','Bhulke','Bokhim','Boya','Champe','Changre','Charambi','Chaukidada','Chhinamakhu','Dalgaun','Deurali','Dewantar','Dhotlekhani','Dobhane','Dummana','Gogane','Gupteshwor','Hasanpur','Helauchha','Homtang','Jarayotar','Keemalung','Keurepani','Khairang','Khartimchha','Khatamma','Khawa','Kota','Kudakkaule','Kulunga','Lekharka','Manebhanjyang','Mulpani','Nagi','Nepaledada','Okhre','Pangcha','Patlepani','Pawala','Pyauli','Ranibas','Sangpang','Sanodumma','Shyamsila','Siddheswor','Sindrang','Taksar','Thidingkha','Thulodumma','Timma','Tiwaribhangyan','Tunggechha','Walangkha','Yaku','Yangpang'],
  chitwan:['Ayodhyapuri', 'Bachhyauli', 'Bagauda', 'Bhandara', 'Bharatpur Municipality', 'Birendranagar', 'Chainpur', 'Chandibhanjyang', 'Dahakhani', 'Darechok', 'Dibyanagar', 'Fulbari', 'Gardi', 'Gitanagar', 'Gunjanagar', 'Jagatpur', 'Jutpani', 'Kabilas', 'Kathar', 'Kaule', 'Khairahani', 'Korak', 'Kumroj', 'Lothar', 'Madikalyanpur', 'Mangalpur', 'Meghauli', 'Padampur', 'Parbatipur', 'Patihani', 'Piple', 'Pithuwa', 'Ratnanagar Municipality', 'Saradanagar', 'Shaktikhor', 'Sibanagar', 'Siddi', 'Sukranagar'],
  dadeldhura:['Ajayameru', 'Alital', 'Amargadhi Municipality', 'Ashigram', 'Bagarkot', 'Belapur', 'Bhadrapur', 'Bhageswor', 'Chipur', 'Dewaldibyapur', 'Ganeshpur', 'Gankhet', 'Jogbuda', 'Kailapalamandau', 'Koteli', 'Manilek', 'Mashtamandau', 'Nawadurga', 'Rupal', 'Samejee', 'Sirsha'],
  dailekh:['Awalparajul', 'Badabhairab', 'Badakhola', 'Badalamji', 'Baluwatar', 'Bansi', 'Baraha', 'Belpata', 'Bhawani', 'Bindhyabasini', 'Bisalla', 'Chamunda', 'Chauratha', 'Dadaparajul', 'Dullu', 'Gamaudi', 'Gauri', 'Goganpani', 'Jaganath', 'Jambukandh', 'Kalbhairab', 'Kalika', 'Kasikandh', 'Katti', 'Khadkawada', 'Kharigera', 'Kusapani', 'Lakandra', 'Lakuri', 'Lalikanda', 'Lyatibindraseni', 'Mairikalikathum', 'Malika', 'Moheltolee', 'Narayan Municipality', 'Naulekatuwal', 'Nepa', 'Nomule', 'Odhari', 'Padukasthan', 'Pagnath', 'Piladi', 'Pipalkot', 'Pusakotchiudi', 'Rakamkarnali', 'Raniban', 'Rawatkot', 'Room', 'Salleri', 'Santalla', 'Seri', 'Sigaudi', 'Sinhasain', 'Tilepata', 'Toli', 'Tolijaisi'],
  dang_deukhuri:['Baghmare', 'Bela', 'Bijauri', 'Chaulahi', 'Dhanauri', 'Dharna', 'Dhikpur', 'Duruwa', 'Gadhawa', 'Gangapraspur', 'Gobardiya', 'Goltakuri', 'Halwar', 'Hansipur', 'Hapur', 'Hekuli', 'Kabhre', 'Koilabas', 'Lalmatiya', 'Laxmipur', 'Loharpani', 'Manpur', 'Narayanpur', 'Panchakule', 'Pawannagar', 'Phulbari', 'Purandhara', 'Rajpur', 'Rampur', 'Saidha', 'Satbariya', 'Saudiyar', 'Shantinagar', 'Shreegaun', 'Sisahaniya', 'Sonpur', 'Syuja', 'Tarigaun', 'Tribhuwannagar Municipality', 'Tulsipur Municipality', 'Urahari'],
  darchula:['Bhagabati','Boharigau','Bramhadev','Byash','Chhapari','Dadakot','Dattu','Dethala','Dhap','Dhari','Dhaulakot','Dhuligada','Eyarkot','Ghusa','Gokuleswor','Guljar','Gwani','Hikila','Hunainath','Huti','Kante','Khalanga','Khandeswori','Khar','Kharkada','Lali','Latinath','Malikarjun','Pipalchauri','Ranisikhar','Rapla','Rithachaupata','Sankarpur','Seri','Sharmauli','Sikhar','Sipti','Sitaula','Sunsera','Tapoban','Uku'],
  dhading:['Aginchok','Baireni','Baseri','Benighat','Bhumesthan','Budhathum','Chainpur','Chhatredyaurali','Darkha','Dhola','Dhussa','Dhuwakot','Gajuri','Goganpani','Gumdi','Jeewanpur','Jharlang','Jogimara','Jyamrung','Kalleri','Katunje','Kewalpur','Khalte','Khari','Kiranchok','Kumpur','Lapa','Mahadevsthan','Maidi','Marpak','Mulpani','Muralibhanjyang','Nalang','Naubise','Nilkantha','Phulkhark','Pida','Reegaun','Salang','Salyankot','Salyantar','Sangkosh','Satyadevi','Semjong','Sertung','Sunaulabazar','Tasarpu','Thakre','Tipling','Tripureswor'],
  dhankuta:['Ahale', 'Ankhisalla', 'Arkhaulejitpur', 'Basantatar', 'Belhara', 'Bhirgaun', 'Bodhe', 'Budhabare', 'Budimorang', 'Chanuwa', 'Chhintang', 'Chungwang', 'Dandabazar', 'Dandagaun', 'Dhankuta Municipality', 'Faksib', 'Falate', 'Ghorlikharka', 'Hathikharka', 'Khoku', 'Khuwafok', 'Kurule', 'Leguwa', 'Mahabharat', 'Marekkatahare', 'Mounabudhuk', 'Mudebas', 'Muga', 'Murtidhunga', 'Pakhribas', 'Parewadin', 'Rajarani', 'Sanne', 'Tankhuwa', 'Telia', 'Vedetar'],
  dhanusa:['Andupatti', 'Aurahi', 'Bafai', 'Bagchaura', 'Bahedabala', 'Bahuarba', 'Balabakhar', 'Balahakathal', 'Balahasadhara', 'Ballagoth', 'Baniniya', 'Baramajhiya', 'Basahiya', 'Basbitti', 'Bateswor', 'Begashivapur', 'Begadawar', 'Bharatpur', 'Bhuchakrapur', 'Bhutahipaterwa', 'Bindhi', 'Bisarbhora', 'Chakkar', 'Chorakoilpur', 'D.Govindapur', 'Debadiha', 'Deuriparbaha', 'Devpurarupetha', 'Dhabouli', 'Dhalkebar', 'Dhanauji', 'Dhanusadham', 'Digambarpur', 'Dubarikothathalekha', 'Duhabi', 'Ekarahi', 'Fulgama', 'Ghodghans', 'Godar', 'Gopalpur', 'Gothkohelpur', 'Hansapurkathpula', 'Hariharpur', 'Harine', 'Hathipurharbara', 'Inarwa', 'Itaharwa', 'Janakpur Municipality', 'Jhatiyahi', 'Jhojhikataiya', 'Kachurithera', 'Kajararamaul', 'Kanakpatti', 'Khajurichanha', 'Khariyani', 'Kurtha', 'Labatoli', 'Lagmagadhaguthi', 'Lakhouri', 'Lakkad', 'Laxminiwas', 'Laxmipurbagewa', 'Lohana', 'Mahuwa(Pra.Khe)', 'Mahuwa(Pra.Ko)', 'Makhanaha', 'Manshingpatti', 'Marchaijhitakaiya', 'Mithileswormauwahi', 'Mithileswornikas', 'Mukhiyapattimushargiya', 'Nagaraeen', 'Nakatajhijh', 'Nanupatti', 'Nauwakhorprashahi', 'Pachaharwa', 'Patanuka', 'Paterwa', 'Paudeswor', 'Puspalpur', 'Raghunathpur', 'Ramaidaiyabhawadi', 'Sabela', 'Sakhuwamahendranagar', 'Sapahi', 'Satosar', 'Shantipur', 'Siddha', 'Singyahimaidan', 'Sinurjoda', 'Sonigama', 'Sugamadhukarahi', 'Suganikash', 'Tarapattisirsiya', 'Thadijhijha', 'Thillayaduwa', 'Tulsichauda', 'Tulsiyahinikas', 'Tulsiyanijabdi', 'Umaprempur', 'Yadukush', 'Yagyabhumi'],
  dholkha:['Alampu', 'Babare', 'Bhedapu', 'Bhimeshwar Municipality', 'Bhirkot', 'Bhusaphedi', 'Bigu', 'Bocha', 'Bulung', 'Chankhu', 'Chhetrapa', 'Chilankha', 'Chyama', 'Dandakharka', 'Dudhpokhari', 'Phasku', 'Gairimudi', 'Gaurisankar', 'Ghangsukathokar', 'Hawa', 'Japhe', 'Jhule', 'Jhyaku', 'Jiri', 'Jugu', 'Kabhre', 'Kalingchok', 'Katakuti', 'Khare', 'Khopachagu', 'Laduk', 'Lakuridada', 'Lamabagar', 'Lamidada', 'Lapilang', 'Magapauwa', 'Mali', 'Malu', 'Marbu', 'Melung', 'Mirge', 'Namdu', 'Orang', 'Pawati', 'Sahare', 'Sailungeswor', 'Sunakhani', 'Sundrawati', 'Suri', 'Susmachhemawati', 'Syama', 'Thulopatal'],
  dolpa:['Bhijer','Chharka','Dho','Dunai','Jufal','Kaigaun','Kalika','Lawan','Laha','Likhu','Majhfal','Mukot','Narku','Pahada','Phoksundo','Raha','Rimi','Sahartara','Saldang','Sarmi','Suhun','Tinje','Tripurakot'],
  doti:['Banjakakani', 'Banlek', 'Barchhen', 'Basudevi', 'Bhumirajmadau', 'Chawarachautara', 'Chhapali', 'Chhatiwan', 'Dahakalikasthan', 'Daud', 'Dhanglagau', 'Dhirkamandau', 'Dipayal Silgadhi Municipality', 'Durgamadau', 'Gadasera', 'Gaguda', 'Gaihragau', 'Ganjari', 'Ghanteswor', 'Girichauka', 'Jijodamandau', 'Kadamadaun', 'Kalena', 'Kalikasthan', 'Kanachaur', 'Kapalleki', 'Kedarakhada', 'Khatiwada', 'Khirsain', 'Ladagada', 'Lamikhal', 'Lanakedareswor', 'Latamandau', 'Laxminagar', 'Mahadevsthan', 'Mannakapadi', 'Mudabhara', 'Mudhegau', 'Nirauli', 'Pachanali', 'Pokhari', 'Ranagau', 'Sanagau', 'Saraswotinagar', 'Satphari', 'Simchaur', 'Tijali', 'Tikhatar', 'Toleni', 'Wagalek', 'Warpata'],
  gorkha:['Aanppipal', 'Aaruarbang', 'Aaruchanuate', 'Aarupokhari', 'Asrang', 'Baguwa', 'Bakrang', 'Bhirkot', 'Bhumlichok', 'Bihi', 'Borlang', 'Bunkot', 'Chhaikampar', 'Chhoprak', 'Chumchet', 'Chyngli', 'Darbhung', 'Deurali', 'Dhawa', 'Dhuwakot', 'Finam', 'Fujel', 'Gaikhur', 'Gakhu', 'Ghairung', 'Ghyachok', 'Ghyalchok', 'Gumda', 'Hanspur', 'Harmhi', 'Jaubari', 'Kashigaun', 'Kerabari', 'Kerauja', 'Kharibot', 'Khoplang', 'Laprak', 'Lapu', 'Lho', 'Makaising', 'Manakamana', 'Manbu', 'Masel', 'Muchhok', 'Namjung', 'Nareshwor', 'Palumtar', 'Panchkhuwadeurali', 'Pandrung', 'Prithvinarayan Municipality', 'Prok', 'Samagaun', 'Saurpani', 'Shreenathkot', 'Simjung', 'Sirdibas', 'Swara', 'Taklung', 'Takukot', 'Takumajhalakuribot', 'Tandrang', 'Tanglichok', 'Taple', 'Thalajung', 'Thumi', 'Uhya', 'Warpak'],
  gulmi:['Aaglung','Amararbathok','Amarpur','Apchaur','Arbani','Arje','Arkhale','Arkhawang','Arlangkot','Aslewa','Badagaun','Bajhketeria','Baletaksar','Balithum','Bamgha','Bharse','Bhurtung','Birbas','Bisukharka','Chhapahile','Dalamchaur','Darbardevisthan','Darling','Daungha','Dhamir','Dhurkotbastu','Dhurkotbhanbhane','Dhurkotnayagaun','Dhurkotrajasthal','Digam','Dirbung','Dohali','Dubichaur','Foksing','Gaidakot','Gwadha','Gwadi','Hadahade','Hansara','Hardineta','Harewa','Harmichaur','Harrachaur','Hastichaur','Hawangdi','Hunga','Ismarajasthal','Jaisithok','Jayakhani','Johang','Juniya','Juvung','Khadgakot','Kharjyang','Kurgha','Limgha','Malagiri','Marbhung','Musikot','Myalpokhari','Neta','Pallikot','Paralmi','Pauchhiamarayee','Pipaldhara','Purkotdaha','Purtighat','Reemuwa','Rupakot','Ruru','Shantipur','Simichaur','Sirseni','Tamghas','Thanpati','Thulolumpek','Turang','Wagla','Wamitaksar'],
  humla:['Baraigaun','Bargaun','Chhipra','Dandafaya','Darma','Gothi','Hepka','Jair','Kalika','Khagalgaun','Kharpunath','Lali','Limi','Madana','Maila','Melchham','Mimi','Muchu','Raya','Rodikot','Sarkeedeu','Saya(Sama)','Shreenagar','Shreemastha','Simikot','Syada','Thehe',],
  ilam: ['Amchok', 'Bajho', 'Barbote', 'Chameta', 'Chisapani', 'Chulachuli', 'Danabari', 'Dhuseni', 'Ebhang', 'Ektappa', 'Erautar', 'Gajurmukhi', 'Goduk', 'Gorkhe', 'Ilam Municipality', 'Jamuna', 'Jirmale', 'Jitpur', 'Jogmai', 'Kanyam', 'Kolbung', 'Laxmipur', 'Lumde', 'Mabu', 'Mahamai', 'Maimajhuwa', 'Maipokhari', 'Mangalbare', 'Namsaling', 'Nayabazar', 'Panchakanya', 'Pasupatinagar', 'Phakphok', 'Phikalbazar', 'Phuyatappa', 'Puwamajhuwa', 'Pyang', 'Sakfara', 'Sakhejung', 'Samalbung', 'Sangrumba', 'Shantidanda', 'Shantipur', 'Shreeantu', 'Siddhithumka', 'Sopak', 'Soyang', 'Sulubung', 'Sumbek'],
  jajarkot:['Archhani','Bhagawatitol','Bhoor','Daha','Dandagaun','Dasera','Dhime','Garkhakot','Jagatipur','Jhapra','Jungathapachaur','Karkigaun','Khagenkot','Khalanga','Kortrang','Lahai','Majhakot','Nayakwada','Paink','Pajaru','Punama','Ragda','Ramidanda','Rokayagaun','Sakala','Salma','Sima','Suwanauli','Talegaun','Thalaraikar'],
  jhapa : ['Anarmani', 'Arjundhara', 'Bahundangi', 'Baigundhara', 'Balubari', 'Baniyani', 'Bhadrapur Municipality', 'Budhabare', 'Chakchaki', 'Chandragadhi', 'Charpane', 'Damak Municipality', 'Dangibari', 'Dhaijan', 'Dharampur', 'Duwagadhi', 'Garamani', 'Gauradaha', 'Gauriganj', 'Ghailadubba', 'Gherabari', 'Goldhap', 'Haldibari', 'Jalthal', 'Juropani', 'Jyamirgadhi', 'Kechana', 'Khajurgachhi', 'Khudunabari', 'Kohabara', 'Korobari', 'Kumarkhod', 'Lakhanpur', 'Mahabhara', 'Maharanijhoda', 'Maheshpur', 'Mechinagar Municipality', 'Panchgachhi', 'Pathamari', 'Pathariya', 'Prithivinagar', 'Rajgadh', 'Sanischare', 'Satasidham', 'Shantinagar', 'Sharanamati', 'Shivaganj', 'Surunga', 'Tagandubba', 'Topgachchi'],
  jumla:['Badki','Birat','Buvramadichaur','Chandannath','Chhumchaur','Depalgaun','Dhapa','Dillichaur','Garjyangkot','Ghodemahadev','Guthichaur','Haku','Kalikakhetu','Kanakasundari','Kartikswami','Kudari','Labhra','Lihi(Rara)','Mahabepattharkhola','Mahatgaun','Malikabota','Malikathota','Narakot','Pandawagufa','Patarasi','Patmara','Sanigaun','Talium','Tamti','Tatopani'],
  kailali:['Baliya', 'Basauti', 'Beladevipur', 'Bhajani', 'Boniya', 'Chauha', 'Chaumala', 'Dansinhapur', 'Darakh', 'Dhangadi Municipality', 'Dododhara', 'Durgauli', 'Gadariya', 'Geta', 'Godawari', 'Hasuliya', 'Janakinagar', 'Joshipur', 'Khailad', 'Khairala', 'Kotatulsipur', 'Lalbojhi', 'Malakheti', 'Masuriya', 'Mohanyal', 'Munuwa', 'Narayanpur', 'Nigali', 'Pahalmanpur', 'Pandaun', 'Pathariya', 'Pawera', 'Phulwari', 'Pratapapur', 'Ramsikharjhala', 'Ratanpur', 'Sadepani', 'Sahajpur', 'Sreepur', 'Sugarkhal', 'Thapapur', 'Tikapur Municipality', 'Udasipur', 'Urma',],
  kalikot:['Badalkot', 'Chhapre', 'Chilkhaya', 'Daha', 'Dholagoh', 'Gela', 'Jubika', 'Khin', 'Kotbada', 'Kumalgaun', 'Lalu', 'Malkot', 'Manma', 'Marta', 'Mehalmudi', 'Mugraha', 'Mumra', 'Nanikot', 'Odanaku', 'Pakha', 'Phui Mahadev', 'Phukot', 'Ranku', 'Ramnakot', 'Ranchuli', 'Rupsa', 'Sipkhana', 'Syuna', 'Sukatiya', 'Thirpu'],
  kanchanpur:['Baisibichawa', 'Beldandi', 'Chandani', 'Daijee', 'Dekhatbhuli', 'Dodhara', 'Jhalari', 'Kalika', 'Krishnapur', 'Laxmipur', 'Mahendranagar Municipality', 'Parasan', 'Pipaladi', 'Raikawarbichawa', 'Rampurbilaspur', 'Rautelibichawa', 'Sankarpur', 'Sreepur', 'Suda', 'Tribhuwanbast'],
  kapilvastu:['Abhirawa', 'Ajigara', 'Bahadurganj', 'Balaramwapur', 'Baluhawa', 'Banganga', 'Baraipur', 'Barakulpur', 'Basantapur', 'Baskhaur', 'Bedauli', 'Bhagwanpur', 'Bhalubari', 'Bijuwa', 'Birpur', 'Bishunpur', 'Bithuwa', 'Budhi', 'Chanai', 'Dhankauli', 'Dharmpaniya', 'Dohani', 'Dubiya', 'Dumara', 'Fulika', 'Gajehada', 'Ganeshpur', 'Gauri', 'Gotihawa', 'Gugauli', 'Haranampur', 'Harduona', 'Hariharpur', 'Hathausa', 'Hathihawa', 'Jahadi', 'Jawabhari', 'Jayanagar', 'Kajarhawa', 'Kapilbastu Municipality', 'Khurhuriya', 'Kopawa', 'Krishnanagar', 'Kushhawa', 'Labani', 'Lalpur', 'Maharajganj', 'Mahendrakot', 'Mahuwa', 'Malwar', 'Manpur', 'Milmi', 'Motipur', 'Nandanagar', 'Nigalihawa', 'Pakadi', 'Parsohiya', 'Patariya', 'Patna', 'Patthardaihiya', 'Pipara', 'Purusottampur', 'Rajpur', 'Ramnagar', 'Rangapur', 'Sauraha', 'Shipanagar', 'Shivagadhi', 'Shivapur', 'Singhkhor', 'Sirsihawa', 'Sisawa', 'Somdiha', 'Thunhiya', 'Tilaurakot', 'Titirkhi', 'Udayapur', 'Vidhyanagar'],
  kaski:['Arbavijaya', 'Armala', 'Bhachok', 'Bhadauretamagi', 'Bharatpokhari', 'Chapakot', 'Dangsing', 'Deurali', 'Dhampus', 'Dhikurepokhari', 'Dhital', 'Ghachok', 'Ghandruk', 'Hansapur', 'Hemaja', 'Kahun', 'Kalika', 'Kaskikot', 'Kritinachnechaur', 'Lahachok', 'Lamachaur', 'Lekhnath Municipality', 'Lumle', 'Lwangghale', 'Machhapuchchhre', 'Majhthana', 'Mauja', 'Mijuredada', 'Namarjung', 'Nirmalpokhari', 'Parche', 'Pokhara Sub-metropolitan City', 'Pumdibhumdi', 'Puranchaur', 'Reevan', 'Rupakot', 'Saimarang', 'Salyan', 'Sarangkot', 'Sardikhola', 'Siddha', 'Sildujure', 'Thumakodada', 'Thumki', 'Valam'],
  kathmandu:['Aalapot', 'Baadbhanjyang', 'Bajrayogini(Sankhu)', 'Balambu', 'Baluwa', 'Bhadrabas', 'Bhimdhunga', 'Budanilkantha', 'Chalnakhel', 'Chapalibhadrakali', 'Chhaimale', 'Chouketardahachok', 'Chunikhel', 'Daanchhi', 'Daxinkali', 'Dhapasi', 'Dharmasthali', 'Futung', 'Gagalphedi', 'Gokarneswor', 'Goldhunga', 'Gonggabu', 'Gothatar', 'Ichangnarayan', 'Indrayani', 'Jhormahankal', 'Jitpurphedi', 'Jorpati', 'Kabhresthali', 'Kapan', 'Kathmandu Metropolitan City', 'Khadkabhadrakali', 'Kirtipur Municipality', 'Lapsephedi', 'Machhegaun', 'Mahadevathan', 'Mahankal', 'Manmaiju', 'Matatirtha', 'Mulpani', 'Naglebhare', 'Naikapnayabhanjyang', 'Naikappuranobhanjyang', 'Nayapati', 'Pukhulachhi', 'Ramkot', 'Sangla', 'Satikhel', 'Satungal', 'Seuchatar', 'Sheshnarayan', 'Sitapaila', 'Sundarijal', 'Suntol', 'Talkududechour', 'Thankot', 'Tinthana', 'Tokhachandeswori', 'Tokhasarswoti'],
  kavrepalanchok:['Anaikot', 'Baldthali', 'Balting', 'Baluwapatideupur', 'Banakhuchor', 'Banepa Municipality', 'Bekhsimledhartigaun', 'Bhimkhori', 'Bhumlutar', 'Birtadeurali', 'Boldefediche', 'Budhakhani', 'Chalalganeshsthan', 'Chandenimandan', 'Choubas', 'Chyamrangbesi', 'Chyasingkharka', 'Dandagaun', 'Dapchachatraibhanjha', 'Daraunepokhari', 'Deuvumibaluwa', 'Devitar', 'Dhulikhel Municipality', 'Dhunkharka', 'Dhusenisiwalaya', 'Dolalghat', 'Falatebhumlu', 'Falemetar', 'Foksingtar', 'Gairibisounadeupur', 'Ghartichhap', 'Gokule', 'Gothpani', 'Hoksebazar', 'Jaisithokmandan', 'Jyamdimandan', 'Kalatibhumidanda', 'Kanpurkalapani', 'Kartikedeurali', 'Katunjebesi', 'Kavrenityachandeswor', 'Khaharepangu', 'Khanalthok', 'Kharelthok', 'Kharpachok', 'Kolatibhumlu', 'Koshidekha', 'Kuruwaschapakhori', 'Kushadevi', 'Machchhegaun', 'Madankundari', 'Mahadevsthanmandan', 'Mahadevtar', 'Mahankalchaur', 'Mahendrajyoti', 'Majhifeda', 'Mangaltar', 'Mathurapatifulbari', 'Methinkot', 'Milche', 'Nagregagarche', 'Nala(Ugrachandi)', 'Nasikasthansanga', 'Nayagaundeupur', 'Panauti Municipality', 'Panchkhal', 'Patalekhet', 'Pokharichauri', 'Pokharinarayansthan', 'Puranogaundapcha', 'Raviopi', 'Ryalebhir', 'Saldhara', 'Sallebhumlu', 'Salmechakala(Taldhunga)', 'Sankhupatichour', 'Sanowangthali', 'Saping', 'Saradabatase', 'Saramthali', 'Sarasyunkhark', 'Sathigharbhagawati', 'Sikharambote', 'Simalchoursyampati', 'Simthali', 'Sipalichilaune', 'Sisakhani', 'Thuloparsel', 'Tukuchanala', 'Ugratarajanagal'],
  khotang:['Ainselukharka','Arkhaule','Badahare','Badakadiyale','Bahunidanda','Bakachol','Baksila','Bamrang','Barahapokhari','Baspani','Batase','Bijayakharka','Buipa','Chhitapokhari','Chhorambu','Chipring','Chisapani','Chyandada','Chyasmitar','Damarkhushivalaya','Dandagaun','Devisthan','Dhitung','Diktel','Dikuwa','Diplung','Dorpachiuridada','Dubekoldada','Dumredharapani','Durchhim','Faktang','Haunchur','Indranipokhari','Jalapa','Jyamire','Kahule','Khalle','Kharmi','Kharpa','Khartanchha','Khidima','Khotangbazar','Kuvinde','Lafyang','Lamidada','Lichkiramche','Linkuwapokhari','Magpa','Mahadevasthan','Mangaltar','Mattimbirta','Mauwabote','Nerpa','Nirmalidada','Nunthala','Patheka','Pauwasera','Phedi','R.Maheswori','Rajapani','Rakhabangdel','Rakhadipsung','Ratanchamajhagau','Ribdungjaleswor','Sa.Chhitapokhari','Salle','Sapteswor','Saunechaur','Sawakatahare','Simpani','Sungdel','Suntale','Temma','Woplukha','Wopung','Yamkha'],
  lalitpur:['Ashrang', 'Badikhel', 'Bhardev', 'Bhattedanda', 'Bisankhunarayan', 'Bukhel', 'Bungamati', 'Chandanpur', 'Chapagaun', 'Chhampi', 'Choughare', 'Dalchoki', 'Devichour', 'Dhapakhel', 'Dhusel', 'Dukuchhap', 'Gimdi', 'Godamchaur', 'Godawari', 'Gotikhel', 'Harisiddhi', 'Ikudol', 'Imadol', 'Jharuwarasi', 'Kaleswor', 'Khokana', 'Lalitpur Sub Metropolitan City', 'Lamatar', 'Lele', 'Lubhu', 'Malta', 'Manikhel', 'Nallu', 'Pyutar', 'Sainbu', 'Sankhu', 'Siddhipur', 'Sunakothi', 'Thaiba', 'Thecho', 'Thuladurlung', 'Tikathali'],
  lamjung:['Archalbot','Bahundanda','Bajhakhet','Balungpani','Bangre','Bansar','Besishahar','Bhalayakharka','Bharte','Bhoje','Bhorletar','Bhoteoodar','Bhujung','Bhulbhule','Bichaur','Chakratirtha','Chandisthan','Chandreshwor','Chiti','Dhamilikuwa','Dhodeni','Dhuseni','Dudhpokhari','Duradanda','Faleni','Gauda','Gaunshahar','Ghanpokhara','Ghermu','Gilunng','Hiletaksar','Ilampokhari','Isaneshwor','Jita','Karapu','Khudi','Kolki','Kunchha','Maling','Mohoriyakot','Nalma','Nauthar','Neta','Pachok','Parewadada','Pasagaun','Puranokot','Pyarjung','Ramgha','Samibhanjyang','Shreebhanjyang','Simpani','Sindure','Sundarbazar','Suryapal','Taghring','Tandrang(Taksar)','Tarku','Tarkughat','Udipur','Uttarkanya'],
  mahottari:['Anakar', 'Aurahi', 'Bagada', 'Bairgiyabanchauri', 'Bairgiyalaxminiya', 'Balawa', 'Banaulidonauli', 'Banouta', 'Bardibas', 'Basabitti', 'Bathanaha', 'Belgachhi', 'Bharatpur', 'Bhatauliya', 'Bijayalpura', 'Bramarpura', 'Damhimarayee', 'Dhamaura', 'Dharmapur', 'Dhirapur', 'Ekadarabela', 'Ekarahiya', 'Etaharwakatti', 'Fulahattaparikauli', 'Fulakaha', 'Gaidahabhelpur', 'Gauribas', 'Gaushala', 'Gonarpura', 'Halkhori', 'Hariharpurharinamari', 'Hathilet', 'Hatisarwa', 'Jaleshwar Municipality', 'Khairbanni', 'Khayarmara', 'Khopi', 'Khuttapiparadhi', 'Kisannagar', 'Kolhuwabagaicha', 'Laximiniya', 'Loharpatti', 'Mahadaiyatapanpur', 'Mahottari', 'Maisthan', 'Majhorabishnupur', 'Manara', 'Matihani', 'Meghanathgorahanna', 'Nainhi', 'Nigaul', 'Paraul', 'Parsadewadh', 'Parsapateli', 'Pasupatinagar', 'Pigouna', 'Pipra', 'Pokharibhindasamgrampur', 'Raghunathpur', 'Ramgopalpur', 'Ramnagar', 'Ratauli', 'Sahasaula', 'Sahorawa', 'Sandha', 'Sarpallo', 'Shamsi', 'Shreepur', 'Simardahi', 'Singyahi', 'Sisawakataiya', 'Sonama', 'Sonamai', 'Sonaul', 'Sugavawani', 'Sundarpur', 'Vagaha'],
  makwanpur:['Agara', 'Ambhanjyang', 'Bajrabarahi', 'Basamadi', 'Betini', 'Bhaise', 'Bhartapundyadevi', 'Bhimfedi', 'Budhichaur', 'Chitlang', 'Churiyamai', 'Daman', 'Dandakharka', 'Dhimal', 'Fakhel', 'Faparbari', 'Gogane', 'Handikhola', 'Hatiya', 'Hetauda Municipality', 'Hurnamadi', 'Ipapanchakanya', 'Kalikatar', 'Kankada', 'Khairang', 'Kogate', 'Kulekhani', 'Makwanpurgadhi', 'Manahari', 'Manthali', 'Markhu', 'Namtar', 'Nibuwatar', 'Padampokhari', 'Palung', 'Raigaun', 'Raksirang', 'Sarikhetpalase', 'Shikharpur', 'Shreepurchhatiwan', 'Sisnerimahadevsthan', 'Sukaura', 'Thingan', 'Tistungdeurali'],
  manang:['Bhraka','Chame','Dharapani','Fu','Ghyaru','Khangsar','Manang','Nar','Nyawal','Pisang','Tachibagarchhap','Tankimanang','Thoche'],
  morang: ['Amahibariyati', 'Amardaha', 'Amgachhi', 'Babiyabirta', 'Bahuni', 'Baijanathpur', 'Banigama', 'Baradanga', 'Bayarban', 'Belbari', 'Bhaudaha', 'Bhogateni', 'Biratnagar Sub Metropolitan', 'Budhanagar', 'Dadarbairiya', 'Dainiya', 'Dangihat', 'Dangraha', 'Drabesh', 'Dulari', 'Govindapur', 'Haraicha', 'Hasandaha', 'Hathimudha', 'Hoklabari', 'Indrapur', 'Itahara', 'Jante', 'Jhorahat', 'Jhurkiya', 'Kaseni', 'Katahari', 'Kathamaha', 'Kerabari', 'Keroun', 'Lakhantari', 'Letang', 'Madhumalla', 'Mahadewa', 'Majhare', 'Matigachha', 'Motipur', 'Mrigauliya', 'Necha', 'Pathari', 'Patigaun', 'Pokhariya', 'Rajghat', 'Ramitekhola', 'Rangeli', 'Sanischare', 'Sidharaha', 'Sijuwa', 'Sinhadevisombare', 'Sisabanibadahara', 'Sisawanijahada', 'Sorabhag', 'Sundarpur', 'Takuwa', 'Tandi', 'Tankisinuwari', 'Tetariya', 'Thalaha', 'Urlabari', 'Warangi', 'Yangshila'],
  mugu:['Bhiyee','Dhainakot','Dolphu','Gumtha','Hyanglu','Jima','Karkibada','Kimari','Kotdanda','Mangri','Mugu','Natharpu','Photu','Pina','Pulu','Rara(Gilas)','Rarakalai','Rowa','Ruga','Khaumale','Seri','Shrikot','Shreenagar','Sukhadhik'],
  mustang:['Charang','Chhonhup','Chhoser','Chhusang','Dhami','Jhong','Jomsom','Kagbeni','Kowang','Kunjo','Lete','Lomanthang','Marpha','Muktinath','Surkhang','Tukuche'],
  myagdi:['Arman','Arthunge','Babiyachaur','Bagarkhola','Baranja','Bhakilmi','Bima','Chimkhola','Dagnam','Dana','Darwang','Devisthan','Dhatan','Dowa','Gurjakhani','Histhanmandali','Jhin','Jyamrukot','Kuhun','Kuinemangale','Lulang','Malkwang','Marang','Mudi','Muna','Narchyang','Niskot','Okharbot','Pakhapani','Patlekhet','Pulachaur','Rakhubhagawati','Rakhupiple','Ramche','Ratnechaur','Room','Shikha','Singa','Takam','Tatopani(Bhurung)'],
  nawalparasi:['Agryouli', 'Amarapuri', 'Amraut', 'Badaharadubauliya', 'Baidauli', 'Banjariya', 'Benimanipur', 'Bharatipur', 'Bhujhawa', 'Bulingtar', 'Dadajheritadi', 'Dawannedevi', 'Dedgaun', 'Deurali', 'Devachuli', 'Devagawa', 'Dhaubadi', 'Dhurkot', 'Dibyapuri', 'Dumkibas', 'Gaidakot', 'Gairami', 'Guthiparsauni', 'Guthisuryapura', 'Hakui', 'Harpur', 'Hupsekot', 'Jahada', 'Jamuniya', 'Jaubari', 'Kawaswoti', 'Kolhuwa', 'Kotathar', 'Kudiya', 'Kumarwarti', 'Kusma', 'Mainaghat', 'Makar', 'Manari', 'Mithukaram', 'Mukundapur', 'Naram', 'Narayani', 'Narsahi', 'Nayabelhani', 'Pakalihawa', 'Palhi', 'Panchanagar', 'Parsauni', 'Pithauli', 'Pragatinagar', 'Pratappur', 'Rajahar', 'Rakachuli', 'Rakuwa', 'Ramgram Municipality', 'Ramnagar', 'Rampurkhadauna', 'Rampurkha', 'Ratanapur', 'Ruchang', 'Rupauliya', 'Sanai', 'Sarawal', 'Shivmandir', 'Somani', 'Sukrauli', 'Sunwal', 'Swathi', 'Tamasariya', 'Thulokhairatawa', 'Tilakpur', 'Tribenisusta', 'Upalloarkhale'],
  nuwakot:['Bagesworichokade', 'Balkumari', 'Barsunchet', 'Belkot', 'Beteni', 'Bhadratar', 'Bhalche', 'Bidur Municipality', 'Budhasing', 'Bungtang', 'Charghare', 'Chaturale', 'Chaughada', 'Chauthe', 'Chhap', 'Dangsing', 'Deurali', 'Duipipal', 'Fikuri', 'Ganeshthan', 'Gaunkharka', 'Gerkhu', 'Ghyangphedi', 'Gorsyang', 'Jiling', 'Kabilas', 'Kakani', 'Kalikahalde', 'Kalyanpur', 'Kaule', 'Khadagbhanjyang', 'Kharanitar', 'Kholegaunkhanigaun', 'Kintang', 'Kumari', 'Lachyang', 'Likhu', 'Madanpur', 'Mahakali', 'Manakamana', 'Narjamandap', 'Okharpauwa', 'Panchkanya', 'Ralukadevi', 'Ratmate', 'Rautbesi', 'Salme', 'Samari', 'Samundradevi', 'Samundratar', 'Shikharbesi', 'Sikre', 'Sundaradevi', 'Sunkhani', 'Suryamati', 'Talakhu', 'Taruka', 'Thanapati', 'Thansing', 'Thaprek', 'Tupche', 'Urleni_Bagesworichokade', 'Balkumari', 'Barsunchet', 'Belkot', 'Beteni', 'Bhadratar', 'Bhalche', 'Bidur Municipality', 'Budhasing', 'Bungtang', 'Charghare', 'Chaturale', 'Chaughada', 'Chauthe', 'Chhap', 'Dangsing', 'Deurali', 'Duipipal', 'Fikuri', 'Ganeshthan', 'Gaunkharka', 'Gerkhu', 'Ghyangphedi', 'Gorsyang', 'Jiling', 'Kabilas', 'Kakani', 'Kalikahalde', 'Kalyanpur', 'Kaule', 'Khadagbhanjyang', 'Kharanitar', 'Kholegaunkhanigaun', 'Kintang', 'Kumari', 'Lachyang', 'Likhu', 'Madanpur', 'Mahakali', 'Manakamana', 'Narjamandap', 'Okharpauwa', 'Panchkanya', 'Ralukadevi', 'Ratmate', 'Rautbesi', 'Salme', 'Samari', 'Samundradevi', 'Samundratar', 'Shikharbesi', 'Sikre', 'Sundaradevi', 'Sunkhani', 'Suryamati', 'Talakhu', 'Taruka', 'Thanapati', 'Thansing', 'Thaprek', 'Tupche', 'Urleni'],
  parbat:['Arthardadakharka','Bachchha','Bahakithanti','Bajung','Balakot','Banou','Baskharka','Behulibans','Bhangara','Bhoksing','Bhorle','Bhuktangle','Bihadibarachaur','Bihadiranipani','Bitalawapipaltari','Chitre','Chuwa','Deupurkot','Deurali','Dhairing','Durlung','Falamkhani','Falebasdevisthan','Fulebaskhanigaun','Hosrangdi','Huwas','Karkineta','Katuwachaupari','Khaulalakuri','Khurkot','Kurgha','Kyang','Lekhfant','Limithana','Lunkhudeurali','Majhphantmallaj','Mudikuwa','Nagliwang','Pakhapani','Pakuwa','Pang','Pangrang','Ramjadeurali','Saligram','Salija','Saraukhola','Shankarpokhari','Shivalaya','Taklak','Thanamaulo','Thapathana','Thulipokhari','Tilahar','Tribeni','Urampokhara'],
  parsa:['Alau', 'Amarpatti', 'Auraha', 'Bagahi', 'Bagbana', 'Bageshwaritirtrona', 'Bahauripidari', 'Bahuarbamatha', 'Basadilwa', 'Basantpur', 'Belwaparsouni', 'Beriyabirta', 'Beriyabirta(Wa.Pu.)', 'Bhawanipur', 'Bhedihari', 'Bhisawa', 'Bijbaniya', 'Bindabasini', 'Biranchibarba', 'Birganj Sub Metropolitan City', 'Birwaguthi', 'Bisrampur', 'Chorni', 'Deukhana', 'Dhaubini', 'Dhore', 'Gadi', 'Gamhariya', 'Ghoddaudapipra', 'Govindapur', 'Hariharpur', 'Hariharpurbirta', 'Harpatagunj', 'Harpur', 'Jagaranathpursira', 'Jaimangalapur', 'Janakitala', 'Jeetpur', 'Jhouwaguthi', 'Kauwabankataiya', 'Lahawarthakari', 'Lakhanpur', 'Lalparsa', 'Langadi', 'Lipanibirta', 'Madhubanmathaul', 'Mahadevpatti', 'Mahuwan', 'Mainpur(Pakaha)', 'Maniyari', 'Masihani', 'Mikhampur', 'Mirjapur', 'Mudali', 'Nagardaha', 'Nichuta', 'Nirmalbasti', 'Pancharukhi', 'Parsaunibirta', 'Parsaunimatha', 'Pidariguthi', 'Pokhariya', 'Prasurampur', 'Ramgadhawa', 'Ramnagari', 'Sabaithawa', 'Sakhuwaprasauni', 'Samjhauta', 'Sankarsaraiya', 'Sedhawa', 'Shivaworga', 'Sirsiyakhalwatola', 'Sonbarsa', 'Sreesiya(Nau.Ta.Ja.)', 'Subarnapur', 'Sugaulibirta', 'Sugaulipartewa', 'Supauli', 'Surjaha', 'Thori', 'Tulasibarba', 'Udayapurdhurmi', 'Vauratar'],
  pyuthan:['Arkha','Badikot','Bangesal','Baraula','Barjiwang','Belwaspur','Bhingri','Bijayanagar','Bijubar','Bijuli','Chuja','Dakhanwadi','Damri','Dangwang','Dharampani','Dharmawati','Dhobaghat(Udayapurkot)','Dhuwang','Dungegadi','Gothiwang','Hansapur','Jumrikanda','Khaira','Khawang','Khung','Kochiwang','Ligha','Liwang','Lung','Majhakot','Maranthana','Markawang','Narikot','Nayagaun','Okharkot','Pakala','Phopli','Puja','Pythankhalanga','Rajbara','Ramdi','Ruspurkot','Sari','Swargadwarikhal','Syauliwang','Tiram','Torwang','Tusara','Wangemarot'],
  palpa:['Archale', 'Argali', 'Bahadurpur', 'Baldengadhi', 'Bandipokhara', 'Barangdi', 'Bhairabsthan', 'Bhuwanpokhari', 'Birkot', 'Bodhapokharathok', 'Boudhagumba', 'Chappani', 'Chhahara', 'Chidipani', 'Chirtungdhara', 'Darchha', 'Darlamdanda', 'Deurali', 'Devinagar', 'Dobhan', 'Fek', 'Foksingkot', 'Gadakot', 'Galdha', 'Gejha', 'Gothadi', 'Haklang', 'Humin', 'Hungi', 'Jalpa', 'Jhadewa', 'Jhirubas', 'Juthapauwa', 'Jyamire', 'Kachal', 'Kaseni', 'Khaliban', 'Khanichhap', 'Khanigau', 'Khasyoli', 'Khyaha', 'Koldada', 'Kusumkhola', 'Madanpokhara', 'Masyam', 'Mityal', 'Mujhung', 'Nayarnamtales', 'Palungmainadi', 'Pipaldada', 'Pokharathok', 'Rahabas', 'Rampur', 'Ringneraha', 'Rupse', 'Sahalkot', 'Satyawati', 'Siddheshwor', 'Siluwa', 'Somadi', 'Tahu', 'Tansen Municipality', 'Telgha', 'Timure', 'Wakamalang', 'Yamgha'],
  ramechhap:['Bamtibhandar','Betali','Bethan','Bhadaure','Bhatauli','Bhirpani','Bhujee','Bijulikot','Chanakhu','Chisapani','Chuchure','Dadhuwa','Deurali','Dimipokhari','Doramba','Duragau','Farpu','Gelu','Goswara','Gothgau','Gumdel','Gunsibhadaure','Guptesor','Hiledevi','Himganga','Kathjor','Khadadevi','Khaniyapani','Khimti','Kubukasthali','Lakhanpur','Majuwa','Makadum','Maluwajor','Manthali','Nagadaha','Namadi','Okhreni','Pakarbas','Phulasi','Pinkhuri','Pritee','Puranagau','Rakathum','Ramechhap','Rampur','Rasanalu','Saipu','Salupati','Sanghutar','Sukajor','Sunarpani','Those','Tilpung','Tokarpur'],
  rasuwa:['Bhorle','Bridhim','Chilime','Dandagoun','Dhunche','Gatlang','Goljung','Haku','Jibjibe(Nilkantha)','Laharepouwa','Langtang','Ramche','Saramthali','Syafru','Thulogoun','Thuman','Timure','Yarsa'],
  rautahat:['Ajagabi', 'Akolawa', 'Auraiya', 'Badharwa', 'Bagahi', 'Bahuwamadanpur', 'Bairiya', 'Banjaraha', 'Bariyarpur', 'Basantapatti', 'Basatpur', 'Basbitijingadiya', 'Bhalohiya(Pipra)', 'Bhediyahi', 'Birtiprastoka', 'Bishrampur', 'Bisunpurwamanpur', 'Brahmapuri', 'Chandranigahapur', 'Debahi', 'Dharampur', 'Dharhari', 'Dipahi', 'Dumariya(Matiauna)', 'Dumriya(Paroha)', 'Fatuhamaheshpur', 'Fatuwaharsaha', 'Gadhi(Bhanawanpur)', 'Gamhariyabirta', 'Gamhariyaparsa', 'Gangapipara', 'Garudabairiya', 'Gaur Municipality', 'Gedahiguthi', 'Hadiryapaltuwa', 'Hajminiya', 'Hathiyahi', 'Iharbarijyutahi', 'Inaruwa', 'Jatahara', 'Jayanagar', 'Jethrahiya', 'Jhunkhunwa', 'Jingadawabelbichwa', 'Jowaha(Jokaha)', 'Judibela', 'Kakanpur', 'Karkachkarmaiya', 'Karuniya', 'Katahariya', 'Khesarhiya', 'Laxminiya', 'Laxmipur(Do)', 'Laxmipurbelbichawa', 'Lokaha', 'Madhopur', 'Mahamadpur', 'Malahi', 'Maryadpur', 'Masedawa', 'Mathiya', 'Matsari', 'Mithuawa', 'Mudwalawa', 'Narkatiyaguthi', 'Pacharukhi', 'Pataura', 'Patharabudharampur', 'Paurai', 'Piparapokhariya', 'Pipariya(Dostiya)', 'Pipariya(Paroha)', 'Piprabhagwanpur', 'Piprarajbara', 'Pothiyahi', 'Pratappurpaltuwa', 'Prempurgunahi', 'Raghunathpur', 'Rajdevi', 'Rajpurfarhadawa', 'Rajpurtulsi', 'Ramolibairiya', 'Rampurkhap', 'Rangapur', 'Sakhuawa', 'Sakhuwadhamaura', 'Samanpur', 'Sangrampur', 'Santapur(Dostiya)', 'Santpur(Matiaun)', 'Sarmujawa', 'Saruatha', 'Saunaraniya', 'Shitalpurbairgania', 'Simarabhawanipur', 'Tejapakar', 'Tengraha'],
  rolpa:['Aresh','Bhawang','Bhirul','Budagaun','Dhawang','Dubaring','Dubidanda','Eriwang','Fagaam','Gaam','Gairigaun','Gajul','Ghartigaun','Ghodagaun','Gumchal','Harjang','Jailwang','Jaimakasala','Jankot','Jaulipokhari','Jedwang','Jhenam','Jinawang','Jungar','Kareti','Khumel','Khungri','Korchawang','Kotgaun','Kureli','Liwang','Masina','Mijhing','Nuwagaun','Pachhawang','Pakhapani','Pang','Rangkot','Rangsi','Rank','Sakhi','Seram','Sirpa','Siuri','Talawang','Tewang','Thawang','Uwa','Wadachaur','Whama','Wot'],
  rukum:['Aathbisdanda','Aathbiskot','Arma','Baflikot','Bhalakacha','Chaurjahari','Chhiwang','Chokhawang','Chunwang','Duli','Garayala','Gautamkot','Ghetma','Hukam','Jang','Jhula','Kanda','Kankri','Khara','Kholagaun','Kol','Kotjahari','Magma','Mahat','Morawang','Muru','Musikotkhalanga','Nuwakot','Pipal','Pokhara','Purtimkanda','Pwang','Pyaugha','Rangsi','Ranmamaikot','Rugha','Sankha','Simli','Sisne','Sobha','Syalagadi','Syalapakha','Taksera'],
  rupandehi:['Aama', 'Aanandaban', 'Amuwa', 'Asurena', 'Bagaha', 'Bagauli', 'Bairghat', 'Basantapur', 'Betakuiya', 'Bhagawanpur', 'Bisunpura', 'Bodabar', 'Bogadi', 'Butawal Municipality', 'Chhipagada', 'Chhotakiramnagar', 'Chilhiya', 'Dayanagar', 'Devadaha', 'Dhakadhai', 'Dhamauli', 'Dudharakchhe', 'Ekala', 'Farena', 'Gajedi', 'Gangoliya', 'Gonaha', 'Harnaiya', 'Hatibangai', 'Hatipharsatikar', 'Jogada', 'Kamahariya', 'Karahiya', 'Karauta', 'Kerbani', 'Khadawabangai', 'Khudabagar', 'Lumbini', 'Madhbaliya', 'Madhuwani', 'Mainahiya', 'Majhagawa', 'Makrahar', 'Manmateriya', 'Manpakadi', 'Maryadpur', 'Masina', 'Motipur', 'Padsari', 'Pajarkatti', 'Pakadisakron', 'Parroha', 'Patekhouli', 'Pokharvindi', 'Rayapur', 'Roinihawa', 'Rudrapur', 'Sadi', 'Saljhundi', 'Sameramarchwar', 'Semalar', 'Shankarnagar', 'Siddharthanagar Municipality', 'Sikatahan', 'Silautiya', 'Sipawa', 'Sourahapharsatikar', 'Suryapura', 'Tenuhawa', 'Thumhawapiprahawa', 'Tikuligadh'],
  salyan:['Badagaun','Waphukhola','Bajhkanda','Bame','Bhalchaur','Chadekareni','Chhayachhetra','Damachaur','Dandagaun','Darmakot','Devsthal','Dhanjaripipal','Dhakadam','Dhanwang','Hiwalcha','Jimali','Kabhrechaur','Kajeri','Kalagaun','Kalimatikalche','Kalimatirampur','Karagithi','Kavra','Khalanga','Korbangjhimpe','Kotbara','Kotmola','Kubhindedaha','Laksmipur','Lekhpokhara','Majhkanda','Marke','Marmaparikanda','Mulkhola','Nigalchula','Phalawang','Pipalneta','Rim','Saijuwaltakura','Sarpanigarpa','Shivarath','Siddheshwari','Sinbang','Suikot','Syanikhal','Tharmare','Tribeni'],
  sankhuwasabha:['Ankhibhui', 'Bahrabise', 'Bala', 'Bana', 'Baneswor', 'Chainpur', 'Chepuwa', 'Dhupu', 'Diding', 'Hatiya', 'Jaljala', 'Keemathnka', 'Khandbari Municipality', 'Kharang', 'Madimulkharka', 'Madirambeni', 'Makalu', 'Mamling', 'Mangtewa', 'Matsyapokhari', 'Mawadin', 'Num', 'Nundhaki', 'Pathibhara', 'Pawakhola', 'Sabhapokhari', 'Siddhakali', 'Siddhapokhari', 'Sisuwakhola', 'Sitalpati', 'Syabun', 'Tamafok', 'Tamku', 'Yafu'],
  saptari:['Arnaha', 'Aurahi', 'Badgama', 'Bairawa', 'Bakdhauwa', 'Bamangamakatti', 'Banainiya', 'Banarjhula', 'Banaula', 'Banauli', 'Baramjhiya', 'Barsain(Ko.)', 'Basbalpur', 'Basbiti', 'Bathanaha', 'Belhi', 'Belhichapena', 'Bhagawatpur', 'Bhangaha', 'Bhardaha', 'Bhutahi', 'Birpurbarahi', 'Bishahariya', 'Bodebarsaien', 'Boriya', 'Brahmapur', 'Chhinnamasta', 'Dadha', 'Daulatpur', 'Deuri', 'Deurimaruwa', 'Dhanagadi', 'Dharampur', 'Dhodhanpur', 'Didhawa', 'Diman', 'Fakira', 'Farseth', 'Fatepur', 'Fulkahi', 'Gamhariyaparwaha', 'Gobargada', 'Goithi', 'Hanumannagar', 'Hardiya', 'Hariharpur', 'Haripur', 'Inarwa', 'Inarwafulpariya', 'Itaharibishnupur', 'Jagatpur', 'Jamunimadhepura', 'Jandaul', 'Jhutaki', 'Joginiya-1', 'Joginiya-2', 'Kabilash', 'Kachan', 'Kalyanpur', 'Kamalpur', 'Kanchanpur', 'Kataiya', 'Khadgapur', 'Khojpur', 'Khoksarparbaha', 'Ko.Madhepura', 'Kochabakhari', 'Koiladi', 'Kushaha', 'Lalapati', 'Launiya', 'Lohajara', 'Madhawapur', 'Madhupati', 'Mahadeva', 'Mainakaderi', 'Mainasahasrabahu', 'Malekpur', 'Maleth', 'Malhanama', 'Malhaniya', 'Manraja', 'Mauwaha', 'Mohanpur', 'Nardho', 'Negada', 'Odraha', 'Pakari', 'Pansera', 'Paterwa', 'Pato', 'Patthargada', 'Pipra(Purba)', 'Pipra(West)', 'Portaha', 'Prasabani', 'Rajbiraj Municipality', 'Ramnagar', 'Rampuramalhaniya', 'Rampurjamuwa', 'Rautahat', 'Rayapur', 'Rupnagar', 'Sambhunath', 'Sankarpura', 'Saraswor', 'Simrahasigiyoun', 'Siswabeihi', 'Sitapur', 'Tarahi', 'Terahota', 'Theliya', 'Tikuliya', 'Tilathi', 'Trikola'],
  sarlahi:['Achalgadh', 'Arnaha', 'Atrouli', 'Aurahi', 'Babarganj', 'Bagdaha', 'Bahadurpur', 'Balara', 'Baraudhoran', 'Barahathawa', 'Basantapur', 'Batraul', 'Bela', 'Belhi', 'Belwajabdi', 'Bhadsar', 'Bhagawatipur', 'Bhaktipur', 'Bhawanipur', 'Brahmapuri', 'Chandranagar', 'Chhataul', 'Chhatona', 'Dhanakaulpachhiyati', 'Dhanakaulpurba', 'Dhangada', 'Dhungrekhola', 'Dhurkauli', 'Dumariya', 'Farahadawa', 'Fulparasi', 'Gadahiyabairi', 'Gamhariya', 'Godeta', 'Gourishankar', 'Hajariya', 'Harakthawa', 'Haripur', 'Haripurwa', 'Hariyon', 'Hathiyol', 'Hempur', 'Ishworpur', 'Jabdi', 'Jamuniya', 'Janakinagar', 'Jingadawa', 'Kabilasi', 'Kalinjor', 'Karmaiya', 'Khirwa', 'Khoriya', 'Khutauna', 'Kisanpur', 'Kodena', 'Lalbandi', 'Laukath', 'Laxmipurkodraha', 'Laxmipursu.', 'Madhubangoth', 'Madhubani', 'Mahinathpur', 'Mailhi', 'Malangawa  Municipality', 'Manpur', 'Mirjapur', 'Mohanpur', 'Motipur', 'Murtiya', 'Musauli', 'Narayankhola', 'Narayanpur', 'Netraganj', 'Noukailawa', 'Parsa', 'Parwanipur', 'Pattharkot', 'Pidari', 'Pidariya', 'Pipariya', 'Rajghat', 'Ramban', 'Ramnagarbahaur', 'Raniganj', 'Rohuwa', 'Sakraul', 'Salempur', 'Sangrampur', 'Sankarpur', 'Sasapur', 'Shreepur', 'Sikhauna', 'Simara', 'Sisotiya', 'Sisout', 'Sohadawa', 'Sudama', 'Sundarpur', 'Sundarpurchuldawa', 'Tribhuwannagar'],
  sindhuli:['Amale', 'Arunthakur', 'Bahuntilpung', 'Balajor', 'Baseshwor', 'Bastipur', 'Belghari', 'Bhadrakali', 'Bhimeshwor', 'Bhimsthan', 'Bhuwaneshorigwaltar', 'Bitijorbagaiya', 'Dadiguranshe', 'Dudbhanjyang', 'Dudhouli', 'Hariharpurgadhi', 'Harsahi', 'Hatpate', 'Jalkanya', 'Jarayotar', 'Jhangajholiralmata', 'Jinakhu', 'Kakurthakur', 'Kalpabrishykha', 'Kamalamai Municipality', 'Kapilakot', 'Khangsang', 'Kholagaun', 'Kuseswordumja', 'Kyaneshwor', 'Ladabhir(Mahendra)', 'Lampantar', 'Mahadevdada', 'Mahadevsthan', 'Mahendrajhayadi', 'Majhuwa', 'Netrakali', 'Nipane', 'Pipalmadi', 'Puranojhangajholi', 'Ranibas', 'Ranichuri', 'Ratanchura', 'Ratnawati', 'Santeswori(Rampur)', 'Sirthouli', 'Sitalpati', 'Solpathana', 'Sunampokhari', 'Tamajor', 'Tandi', 'Tinkanya', 'Tosramkhola', 'Tribhuvanambote'],
  sindhupalchok:['Atarpur','Badegau','Bansbari','Banskharka','Baramchi','Barhabise','Baruwa','Batase','Bhimtar','Bhotasipa','Bhotenamlang','Bhotechaur','Choukati','Choutara','Dhumthang','Dubachour','Fatakshila','Fulpingdandagau','Fulpingkatti','Fulpingkot','Gati','Ghorthali','Ghuskun','Gloche','Gumba','Gunsakot','Hagam','Haibung','Helumbu','Ichok','Irkhu','Jalbire','Jethal','Jyamire','Kadambas','Kalika','Karthali','Kiwool','Kubhinde','Kunchok','Langarche','Lisankhu','Listikot','Mahankal','Maneswor','Mankha','Marming','Melamchi','Motang','Nawalpur','Pagretar','Palchok','Pangtang','Petaku','Pipaldanda','Piskar','Ramche','Sangachok','Sanusiruwari','Selang','Sikharpur','Sindhukot','Sipapokhare','Sipalkavre','Sunkhani','Syaulebazar','Talramarang','Tatopani','Tauthali','Tekanpur','Thakani','Thampalchhap','Thanpalkot','Thokarpa','Thulodhading','Thulopakhar','Thulosirubari','Thumpakhar','Yamunadanda'],
  siraha:['Arnamalalpur', 'Arnamarampur', 'Asanpur', 'Ashokpurbalkawa', 'Aurahi', 'Ayodhyanagar', 'Badharamal', 'Barchhawa', 'Bariyarpatti', 'Bastipur', 'Belaha', 'Belhi', 'Betauna', 'Bhadaiya', 'Bhaganpur', 'Bhagawatipur', 'Bhawanipur', 'Bhawanpurkalabanzar', 'Bhokraha', 'Bishnupurpra.Ma.', 'Bishnupurpra.Ra', 'Bishnupurkatti', 'Brahmagaughadi', 'Chandraayodhyapur', 'Chandralalpur', 'Chandrodayapur', 'Chatari', 'Chikana', 'Devipur', 'Dhangadi', 'Dhodhana', 'Dumari', 'Durgapur', 'Fulbariya', 'Fulkahakati', 'Gadha', 'Gauripur', 'Gautari', 'Govindapurmalahanama', 'Govindpurtaregana', 'Hakpara', 'Hanumannagar', 'Hanumannagar(Pra.Dha.)', 'Harakatti', 'Inarwa', 'Itarhawa', 'Itariparsahi', 'Itatar', 'Jamadaha', 'Janakinagar', 'Jighaul', 'Kabilasi', 'Kachanari', 'Kalyanpurjabadi', 'Kalyanpurkalabanzar', 'Karjanha', 'Kharukyanhi', 'Khirauna', 'Krishnapurbirta', 'Kushahalaxininiya', 'Lagadigadiyani', 'Lagadigodh', 'Lahan Municipality', 'Lalpur', 'Laxminiya', 'Laxmipur(Pra.Ma.)', 'Laxmipurpatari', 'Madar', 'Mahadewaportaha', 'Mahanaur', 'Maheshpurgamharia', 'Maheshpurpatari', 'Majhauliya', 'Majhaura', 'Malhaniyagamharia', 'Malhaniyakhori', 'Mauwahi', 'Media', 'Mohanpurkamalpur', 'Muksar', 'Nahararigoul', 'Narahabalkawa', 'Navarajpur', 'Padariyatharutol', 'Piprapra.Dha', 'Piprapra.Pi', 'Pokharbhinda', 'Radhopur', 'Rajpur', 'Ramnagarmirchaiya', 'Rampurbirta', 'Sakhuwanankarkatti', 'Sanhaitha', 'Sarswar', 'Sikron', 'Silorbapachhawari', 'Siraha Municipality', 'Sisawani', 'Sitapurpra.Da.', 'Sitapurpra.Ra.', 'Sonmatimajhaura', 'Sothiyan', 'Sukhachina', 'Sukhipur', 'Tenuwapatti', 'Thalahakataha', 'Tulsipur', 'Vidhyanagar'],
  solukhumbu:['Baku','Basa','Beni','Bhakanje','Bung','Chaulakharka','Chaurikharka','Chheskam','Deusa','Garma','Goli','Gorakhani','Gudel','Jubing','Jubu','Kaku','Kangel','Khumjung','Kureng','Lodingtamakhani','Lokhim','Mabe(Pawai)','Mukali','Namche','Nechabatase','Nechabedghari','Nele','Panchan','Salleri','Salyan','Sotang','Takasindu','Tapting','Tingla'],
  sunsari:['Aekamba', 'Amaduwa', 'Amahibelaha', 'Aurabarni', 'Babiya', 'Bakalauri', 'Barahachhetra', 'Basantapur', 'Bhadgausinawari', 'Bhaluwa', 'Bharaul', 'Bhokraha', 'Bishnupaduka', 'Chadwela', 'Chhitaha', 'Chimdi', 'Dewanganj', 'Dharan Municipality', 'Dhuskee', 'Duhabi', 'Dumaraha', 'Gautampur', 'Hanshposha', 'Harinagar', 'Haripur', 'Inaruwa Municipality', 'Ithari Municipality', 'Jalpapur', 'Kaptanganj', 'Khanar', 'Laukahi', 'Madhelee', 'Madhesa', 'Madhuwan', 'Madhyeharsahi', 'Mahendranagar', 'Narshinhatappu', 'Pakali', 'Panchakanya', 'Paschimkasuha', 'Prakashpur', 'Purbakushaha', 'Ramganjbelgachhi', 'Ramganjsenuwari', 'Ramnagarbhutaha', 'Sahebganj', 'Santerjhora', 'Simariya', 'Singiya', 'Sonapur', 'Sripurjabdi', 'Tanamuna'],
  surkhet:['Agragaun', 'Awalching', 'Babiyachaur', 'Bajedichaur', 'Betan', 'Bidyapur', 'Bijaura', 'Birendranagar Municipality', 'Chapre', 'Chhinchu', 'Dahachaur', 'Dandakhali', 'Dasarathpur', 'Dharapani', 'Gadibayalkada', 'Garpan', 'Ghatgaun', 'Ghoreta', 'Ghumkhahare', 'Gumi', 'Guthu', 'Hariharpur', 'Jarbuta', 'Kafalkot', 'Kalyan', 'Kaprichaur', 'Khanikholla', 'Kunathari', 'Lagaam', 'Latikoili', 'Lekhfarsa', 'Lekhgaun', 'Lekhparajul', 'Maintada', 'Malarani', 'Matela', 'Mehelkuna', 'Neta', 'Pamka', 'Pokharikanda', 'Rajena', 'Rakam', 'Ramghat', 'Ranibas', 'Ratu', 'Sahare', 'Salkot', 'Satakhani', 'Taranga', 'Tatopani', 'Uttarganga'],
  syangja:['Alamadevi', 'Arjunchaupari', 'Aruchaur', 'Arukharka', 'Bagefatake', 'Bahakot', 'Benethokdeurali', 'Bhatkhola', 'Bicharichautara', 'Birghaarchale', 'Biruwaarchale', 'Chandibhanjyang', 'Chapakot', 'Chhangchhangdi', 'Chilaunebas', 'Chinnebas', 'Chisapani(Magyam)', 'Chitrebhanjyang', 'Darsingdahathum', 'Dhapuksimalbhanjyang', 'Faparthum', 'Fedikhola', 'Jagatbhanjyang', 'Jagatradevi', 'Kalikakot', 'Kaulmabarahachaur', 'Kewarebhanjyang', 'Khilungdeurali', 'Kichnas', 'Kuwakot', 'Kyakmi', 'Majhakotsivalaya', 'Malunga', 'Malyangkot', 'Manakamana', 'Nibuwakharka', 'Oraste', 'Pakwadi', 'Panchamul', 'Pauwegaude', 'Pelakot', 'Pelkachaur', 'Pidikhola', 'Putalibazar Municipality', 'Rangvang', 'Rapakot', 'Ratnapur', 'Sakhar', 'Sataudarau', 'Sekham', 'Setidobhan', 'Shreekrishnagandaki', 'Sirsekot', 'Sworek', 'Taksar', 'Thuladihi', 'Thumpokhara', 'Tindobate', 'Tulsibhanjyang', 'Waling Municipality', 'Wangsingdeurali', 'Yaladi'],
  tanahu:['Anbukhaireni', 'Arunodaya', 'Baidi', 'Bandipur', 'Barbhanjyang', 'Basantapur', 'Bhanu', 'Bhanumati', 'Bhimad', 'Bhirkot', 'Byas Municipality', 'Chhang', 'Chhimkeshwori', 'Chhipchhipe', 'Chokchisapani', 'Deurali', 'Devghat', 'Dharampani', 'Dhorfirdi', 'Dulegaunda', 'Firfire', 'Gajarkot', 'Ghansikuwa', 'Jamunebhanjyang', 'Kahushivapur', 'Keshavtar', 'Khairenitar', 'Kihun', 'Kota', 'Kotdarbar', 'Kyamin', 'Majhakot', 'Manpang', 'Pokharibhanjyang', 'Purkot', 'Raipur', 'Ramjakot', 'Ranipokhari(Resing)', 'Risti', 'Rupakot', 'Satiswara', 'Shambubhagawatipur', 'Shymgha', 'Sundhara(Ghiring)', 'Tanahunsur', 'Thaprek', 'Virlung'],
  taplejung: ['Ankhop','Chaksibote','Change','Dhungesaghu','Dokhu','Dummrise','Ekhabu','Hangdeva','Hangpang','Kalikhola','Khamlung','Khejenim','Khewang','Khokling','Lelep','Limbudin','Lingtep','Linkhim','Liwang','Mamankhe','Mehele','Nalbu','Nankholyang','Nidhuradin','Olangchunggola','Papung','Pedang','Phakumba','Phawakhola','Phulbari','Phungling','Phurumbu','Sadewa','Sangu','Santhakra','Sanwa','Sawadin','Sawalakhu','Sikaicha','Sinam','Surumakhim','Tapethok','Tellok','Thechambu','Thinglabu','Thukima','Thumbedin','Tiringe','Yamfudin',
  ],
  terhathum:['Ambung','Angdeem','Basantapur','Chhatedhunga','Chuhandanda','Dangapa','Eseebu','Ewa','Hamarjung','Hwaku','Jaljale','Jirikhinti','Khamlalung','Morahang','Myanglung','Okhare','Oyakjung','Panchakanyapokhari','Phakchamara','Phulek','Piple','Pouthak','Sabla','Samdu','Sankrantibazar','Shreejung','Simle','Solma','Sudap','Sungnam','Tamfula','Thoklung'],
  udayapur:['Aaptar', 'Balamta', 'Baraha', 'Barai', 'Basabote', 'Bashaha', 'Beltar', 'Bhuttar', 'Chaudandi', 'Dumre', 'Hadiya', 'Hardeni', 'Iname', 'Jalpachilaune', 'Jante', 'Jogidaha', 'Katari', 'Katunjebawala', 'Khanbu', 'Laphagau', 'Lekhani', 'Lekhgau', 'Limpatar', 'Mainamiani', 'Nametar', 'Okhale', 'Pachchawati', 'Pokhari', 'Rauta', 'Risku', 'Rupatar', 'Saune', 'Shorungchabise', 'Sidhdipur', 'Sirise', 'Sundarpur', 'Tamlida', 'Tapeswori', 'Tawashree', 'Thanagau', 'Thoksila', 'Tribeni', 'Trijuga Municipality', 'Valayadanda', 'Yayankhu']
};

districtEle.addEventListener("click", (e) => {
    const selectedDistrict = e.target.value.toLowerCase();
    let populatedMunicipality = "";

    if (municipalityDetails[selectedDistrict] === undefined) {
        municipalityDetails[selectedDistrict] = [];
    }

    municipalityDetails[selectedDistrict].map((item) => {
        populatedMunicipality += `<option>${item}</option>`;
    });
    municipalityOption.innerHTML = populatedMunicipality;
    return;
});
